### PR TITLE
fix undefined reference to GetConsoleWindow on line 416 of main.c

### PR DESCRIPTION
**Pull request by Antimoney**
The "GetConsoleWindow()" function on line 416 causes an error (undifined reference) when compiling on Windows, it can not be used directly. It should be loaded from kernel32.dll manually. So, I changed
```
HWND ThisWindow = GetConsoleWindow();
```
into
```
HWND ThisWindow = GetProcAddress(GetModuleHandle("kernel32"), "GetConsoleWindow");
```

### CODE REVIEW

**Comment by holmium** [comment]
What compiler do you use?

**Comment by Antimoney** [comment]
code::blocks + gcc

**Comment by holmium** [comment]
Did you define _WIN32_WINNT as 0x0500 or later? As MSDN notes.

**Comment by Antimoney** [comment]
yes, and it won't work.

**Comment by holmium** [comment]
Please define it at the first line of the file.

**Pull request closed without merging**
